# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='song_price',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
