# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_song_song_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
