# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170921_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_desc',
            field=models.TextField(default='', max_length=500),
        ),
    ]
